// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using catalog_service.Data;

#nullable disable

namespace catalog_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524112715_CatalogMigration")]
    partial class CatalogMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("catalog_service.Models.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("channel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChannelId"));

                    b.Property<string>("ChannelDescription")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("channel_description");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("channel_name");

                    b.Property<string>("ChannelProfileUrl")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("channel_profile_url");

                    b.Property<short>("ChannelStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("channel_status")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ChannelId");

                    b.HasIndex("ChannelName")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("channels");
                });

            modelBuilder.Entity("catalog_service.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideoId"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VideoDescription")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("video_description");

                    b.Property<int>("VideoDurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("video_duration_seconds");

                    b.Property<long>("VideoSize")
                        .HasColumnType("bigint")
                        .HasColumnName("video_size");

                    b.Property<short>("VideoStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("video_status")
                        .HasDefaultValueSql("0");

                    b.Property<string>("VideoThumbnailUrl")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("video_thumbnail_url");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("video_title");

                    b.HasKey("VideoId");

                    b.HasIndex("ChannelId");

                    b.ToTable("videos");
                });

            modelBuilder.Entity("catalog_service.Models.VideoAsset", b =>
                {
                    b.Property<int>("VideoAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("video_asset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideoAssetId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ManifestUrl")
                        .IsRequired()
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("manifest_url");

                    b.Property<int>("VideoAssetBitrate")
                        .HasColumnType("int")
                        .HasColumnName("video_asset_bitrate");

                    b.Property<long>("VideoAssetSize")
                        .HasColumnType("bigint")
                        .HasColumnName("video_asset_size");

                    b.Property<short>("VideoAssetStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("video_asset_status")
                        .HasDefaultValueSql("0");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.Property<int>("VideoQuality")
                        .HasColumnType("int")
                        .HasColumnName("video_quality");

                    b.HasKey("VideoAssetId");

                    b.HasIndex("VideoId");

                    b.ToTable("video_assets");
                });

            modelBuilder.Entity("catalog_service.Models.Video", b =>
                {
                    b.HasOne("catalog_service.Models.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("catalog_service.Models.VideoAsset", b =>
                {
                    b.HasOne("catalog_service.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
