"""create_upload_jobs

Revision ID: 4824f2694d51
Revises: 
Create Date: 2026-05-25 02:42:07.148176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4824f2694d51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_jobs',
    sa.Column('upload_job_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('upload_job_status', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('upload_job_blob_path', sa.String(length=2000), nullable=False),
    sa.Column('upload_job_title', sa.String(length=100), nullable=False),
    sa.Column('upload_job_description', sa.String(length=2000), nullable=True),
    sa.Column('upload_job_thumbnail_url', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('upload_job_status >= 0 AND upload_job_status <= 5', name='CK_UploadJob_UploadJobStatus'),
    sa.PrimaryKeyConstraint('upload_job_id')
    )
    op.create_index('idx_upload_jobs_modified_at', 'upload_jobs', ['modified_at'], unique=False, postgresql_where=sa.text('upload_job_status IN (1, 2, 3)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_upload_jobs_modified_at', table_name='upload_jobs', postgresql_where=sa.text('upload_job_status IN (1, 2, 3)'))
    op.drop_table('upload_jobs')
    # ### end Alembic commands ###
